theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.12
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.12/clink.1.3.12.f70397.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.12/clink.1.3.12.f70397_setup.exe
