theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.16
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.16/clink.1.2.16.30196f.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.16/clink.1.2.16.30196f_setup.exe
