theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.39
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.39/clink.1.2.39.ce9d45.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.39/clink.1.2.39.ce9d45_setup.exe
