theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.46
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.46/clink.1.2.46.69fc92.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.46/clink.1.2.46.69fc92_setup.exe
