theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.15
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.15/clink.1.2.15.b4efda.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.15/clink.1.2.15.b4efda_setup.exe
