theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.4
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.4/clink.1.2.4.309a20.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.4/clink.1.2.4.309a20_setup.exe
