theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.3
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.3/clink.1.2.3.e9c3d7.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.3/clink.1.2.3.e9c3d7_setup.exe
