theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.19
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.19/clink.1.2.19.5f3d6d.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.19/clink.1.2.19.5f3d6d_setup.exe
