theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.44
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.44/clink.1.2.44.b7536d.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.44/clink.1.2.44.b7536d_setup.exe
