theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.11
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.11/clink.1.3.11.0c8196.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.11/clink.1.3.11.0c8196_setup.exe
