theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.13
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.13/clink.1.3.13.24b02e.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.13/clink.1.3.13.24b02e_setup.exe
