theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.38
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.38/clink.1.2.38.5f789b.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.38/clink.1.2.38.5f789b_setup.exe
