theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.21
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.21/clink.1.3.21.5eb05f.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.21/clink.1.3.21.5eb05f_setup.exe
