theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.20
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.20/clink.1.2.20.801802.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.20/clink.1.2.20.801802_setup.exe
