theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.7
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.7/clink.1.3.7.4269ce.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.7/clink.1.3.7.4269ce_setup.exe
