theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.30
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.30/clink.1.2.30.0ddffe.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.30/clink.1.2.30.0ddffe_setup.exe
