theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.48
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.48/clink.1.1.48.b96581.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.48/clink.1.1.48.b96581_setup.exe
