theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.31
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.31/clink.1.1.31.b086d5.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.31/clink.1.1.31.b086d5_setup.exe
