theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.46
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.46/clink.1.1.46.b38a09.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.46/clink.1.1.46.b38a09_setup.exe
