theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.50
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.50/clink.1.2.50.f9e6ce.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.50/clink.1.2.50.f9e6ce_setup.exe
