theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.21
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.21/clink.1.2.21.6d8971.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.21/clink.1.2.21.6d8971_setup.exe
