theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.9
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.9/clink.1.3.9.2e99f4.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.9/clink.1.3.9.2e99f4_setup.exe
