theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.17
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.17/clink.1.3.17.0a95d0.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.17/clink.1.3.17.0a95d0_setup.exe
