theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.47
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.47/clink.1.1.47.c54850.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.47/clink.1.1.47.c54850_setup.exe
