theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.2
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.2/clink.1.3.2.222baa.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.2/clink.1.3.2.222baa_setup.exe
