theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.45
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.45/clink.1.1.45.1c3985.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.45/clink.1.1.45.1c3985_setup.exe
