theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.15
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.15/clink.1.3.15.6e6e45.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.15/clink.1.3.15.6e6e45_setup.exe
