theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.44
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.44/clink.1.1.44.35f810.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.44/clink.1.1.44.35f810_setup.exe
