theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.6
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.6/clink.1.3.6.fde87b.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.6/clink.1.3.6.fde87b_setup.exe
