theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.8
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.8/clink.1.3.8.c918a0.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.8/clink.1.3.8.c918a0_setup.exe
