theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.3.20
  download_url: https://github.com/chrisant996/clink/releases/download/v1.3.20/clink.1.3.20.59deed.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.3.20/clink.1.3.20.59deed_setup.exe
