theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.45
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.45/clink.1.2.45.472728.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.45/clink.1.2.45.472728_setup.exe
