theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.32
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.32/clink.1.1.32.d4bad7.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.32/clink.1.1.32.d4bad7_setup.exe
