theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.41
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.41/clink.1.1.41.df7768.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.41/clink.1.1.41.df7768_setup.exe
