theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2/clink.1.2.0.42d871.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2/clink.1.2.0.42d871_setup.exe
