theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.39
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.39/clink.1.1.39.d7c31b.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.39/clink.1.1.39.d7c31b_setup.exe
