theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.37
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.37/clink.1.2.37.de5dfb.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.37/clink.1.2.37.de5dfb_setup.exe
