theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.12
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.12/clink.1.2.12.4a4e22.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.12/clink.1.2.12.4a4e22_setup.exe
