theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.35
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.35/clink.1.2.35.fa2a3e.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.35/clink.1.2.35.fa2a3e_setup.exe
