theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.28
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.28/clink.1.2.28.f398a1.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.28/clink.1.2.28.f398a1_setup.exe
