theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.33
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.33/clink.1.1.33.3e0bbc.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.33/clink.1.1.33.3e0bbc_setup.exe
