theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.35
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.35/clink.1.1.35.b690c0.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.35/clink.1.1.35.b690c0_setup.exe
