theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.25
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.25/clink.1.2.25.e20659.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.25/clink.1.2.25.e20659_setup.exe
