theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.11
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.11/clink.1.2.11.7dc44f.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.11/clink.1.2.11.7dc44f_setup.exe
