theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.40
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.40/clink.1.1.40.31e5f7.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.40/clink.1.1.40.31e5f7_setup.exe
