theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.1.36
  download_url: https://github.com/chrisant996/clink/releases/download/v1.1.36/clink.1.1.36.457450.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.1.36/clink.1.1.36.457450_setup.exe
