theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.2.36
  download_url: https://github.com/chrisant996/clink/releases/download/v1.2.36/clink.1.2.36.0c9eef.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.2.36/clink.1.2.36.0c9eef_setup.exe
